#-----------------------------------------------------------------------------------
# For Neovim and Vim
[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_ft = ['html', 'markdown', 'css', 'javascript', 'typescript']
if = '!exists("g:vscode")'
hook_add = '''
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
if = '!exists("g:vscode")'
hook_add = '''
  nnoremap <M-f> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'dense-analysis/ale'
on_ft = ['nim']
if = '!exists("g:vscode")'
hook_add = '''
  source ~/.config/nvim/pluginconfig/ale-hook.vim
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'rmd']
if = 'has("nvim") && !exists("g:vscode")'
on_i = 1
hook_post_update = 'cd app && yarn install'
hook_add = 'source ~/.config/nvim/pluginconfig/markdown-preview.vim'

[[plugins]]
repo = 'preservim/tagbar'
if = 'has("nvim") && !exists("g:vscode")'
on_i = 1
hook_add = '''
nnoremap <M-t> :TagbarToggle<CR>
'''

#-----------------------------------------------------------------------------------
# For only Neovim

[[plugins]]
repo = 'neovim/nvim-lspconfig'
if = 'has("nvim") && !exists("g:vscode")'
on_i = 1
hook_source = 'source ~/.config/nvim/pluginconfig/nvim-lsp.vim'

# [[plugins]]
# repo = 'steelsojka/completion-buffers'
# if = 'has("nvim") && !exists("g:vscode")'
# on_i = 1

[[plugins]]
repo = 'nvim-lua/completion-nvim'
if = 'has("nvim") && !exists("g:vscode")'
on_i = 1
hook_source = 'source ~/.config/nvim/pluginconfig/vim_lua_completion.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim") && !exists("g:vscode")'
on_i = 1
hook_source = 'source ~/.config/nvim/pluginconfig/nvim-treesitter.vim'


[[plugins]]
repo = 'josa42/nvim-lightline-lsp'
if = 'has("nvim") && !exists("g:vscode")'
on_i = 1
hook_source = '''
  call lightline#lsp#register()
'''
