add_newline = true

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1
style = "#3f3f3f"
format = "[$path [$read_only](bg:$style fg:red)](bg:$style)[](fg:$style) "

[git_branch]
style = "#a8d045"
format = "\b\b[](fg:#3f3f3f bg:$style)[$symbol$branch ](fg:black bg:$style)[](fg:$style) "

[package]
disabled = true

[time]
disabled = false
style = "#3f3f3f"
format = "[$time](bg:$style fg:white)[](fg:$style)"

[character]
success_symbol = ""
error_symbol = ""

[status]
disabled = false
style = "white"
symbol = "😨 "
format = "\b[](fg:#3f3f3f bg:white)[$symbol$status](bg:$style fg:red)[](fg:$style)"
